from __future__ import annotations

import math
import shutil
from dataclasses import dataclass
from pathlib import Path

import cv2
import numpy as np
import pandas as pd
import soundfile as sf
from PIL import Image, ImageDraw


@dataclass(frozen=True, slots=True)
class RealSchemaFixtureSummary:
    output: Path
    manifest: Path
    samples: int
    sessions: int


def _write_video(path: Path, *, fps: float, seed: int) -> None:
    width, height = 160, 96
    writer = cv2.VideoWriter(
        str(path),
        cv2.VideoWriter_fourcc(*"MJPG"),
        fps,
        (width, height),
    )
    if not writer.isOpened():
        raise RuntimeError("OpenCV could not create real-schema fixture AVI")
    rng = np.random.default_rng(seed)
    for frame_index in range(18):
        frame = np.full((height, width, 3), 12, dtype=np.uint8)
        x = 15 + int((width - 30) * frame_index / 17)
        brightness = 80 if frame_index < 5 else 235
        cv2.circle(frame, (x, height // 2), 7, (brightness, brightness, brightness), -1)
        for _ in range(3):
            px = int(np.clip(x + rng.normal(0, 9), 0, width - 1))
            py = int(np.clip(height // 2 + rng.normal(0, 9), 0, height - 1))
            cv2.circle(frame, (px, py), 1, (245, 245, 245), -1)
        writer.write(frame)
    writer.release()


def _write_audio(path: Path, *, sample_rate: int, seed: int) -> None:
    duration = 0.8
    samples = int(sample_rate * duration)
    time_axis = np.arange(samples, dtype=np.float32) / sample_rate
    rng = np.random.default_rng(seed)
    signal = 0.003 * rng.standard_normal(samples).astype(np.float32)
    onset = int(0.18 * sample_rate)
    signal[onset:] += 0.18 * np.sin(2 * np.pi * 760.0 * time_axis[: samples - onset])
    sf.write(path, np.clip(signal, -1.0, 1.0), sample_rate, format="FLAC")


def _write_sensor(
    path: Path,
    *,
    seed: int,
    missing_column: bool = False,
    extra_column: bool = False,
) -> None:
    rng = np.random.default_rng(seed)
    rows = 220
    t = np.arange(rows, dtype=np.float64) * 0.01
    current = np.where(t < 0.15, 0.0, 182.0 + 3.0 * np.sin(2 * np.pi * 2.2 * t))
    current += rng.normal(0.0, 0.7, rows)
    voltage = np.where(t < 0.15, 0.0, 23.8 + 0.4 * np.sin(2 * np.pi * 1.7 * t + 0.3))
    voltage += rng.normal(0.0, 0.08, rows)
    base = pd.Timestamp("2023-04-03T10:00:00")
    timestamps = [base + pd.Timedelta(seconds=float(value)) for value in t]

    data: dict[str, object] = {
        "Date": [stamp.strftime("%m-%d-%y") for stamp in timestamps],
        "Time": [stamp.strftime("%H:%M:%S.%f")[:-3] for stamp in timestamps],
        "Part No": ["fixture-part"] * rows,
        "Pressure": 1.8 + rng.normal(0.0, 0.01, rows),
        "CO2 Weld Flow": 14.2 + rng.normal(0.0, 0.04, rows),
        "Feed": 320.0 + rng.normal(0.0, 0.8, rows),
        "Primary Weld Current": current,
        "Wire Consumed": np.maximum(0.0, t - 0.15) * 2.0,
        "Secondary Weld Voltage": voltage,
        "Remarks": [""] * rows,
    }
    if missing_column:
        del data["Wire Consumed"]
    if extra_column:
        data["Unmapped Diagnostic"] = np.arange(rows) % 7
    pd.DataFrame(data).to_csv(path, index=False)


def _write_images(directory: Path, *, seed: int, corrupt_index: int | None = None) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(seed)
    for index in range(5):
        path = directory / f"post_weld_{index + 1}.jpg"
        if corrupt_index == index:
            path.write_bytes(b"not-a-jpeg-fixture")
            continue
        image = Image.new("RGB", (240, 108), (34, 36, 40))
        draw = ImageDraw.Draw(image)
        y = 54 + int(4 * math.sin(index))
        draw.line((18, y, 222, y), fill=(210, 210, 210), width=5)
        for _ in range(5):
            x = int(rng.integers(30, 210))
            draw.ellipse((x - 2, y - 2, x + 2, y + 2), fill=(245, 245, 245))
        image.save(path, quality=88)


def generate_real_schema_fixture(
    output: Path,
    *,
    force: bool = False,
    seed: int = 20260818,
) -> RealSchemaFixtureSummary:
    """Generate a tiny public-CI fixture shaped like the audited Intel archive.

    The generated bytes are entirely synthetic. Names, manifest path semantics,
    sensor headers, uppercase split labels, 30/31 FPS variation, and selected
    malformed cases intentionally mirror properties that the real-archive audit
    must keep supporting.
    """

    output = output.expanduser().resolve()
    if output.exists() and any(output.iterdir()):
        if not force:
            raise FileExistsError(f"Output is not empty: {output}. Use force=True to replace it.")
        shutil.rmtree(output)
    output.mkdir(parents=True, exist_ok=True)

    # session, sample, category, split, special-case
    plan = [
        (
            "10_good_01_03-20-23_Fe410",
            "04-03-23-0001-00",
            "Good",
            "TRAIN",
            "normal",
        ),
        (
            "10_good_01_03-20-23_Fe410",
            "04-03-23-0002-00",
            "Good",
            "TRAIN",
            "fps31",
        ),
        (
            "10_crater_cracks_7_03-20-23_Fe410",
            "04-03-23-0010-11",
            "Crater_Cracks",
            "VAL",
            "normal",
        ),
        (
            "10_crater_cracks_7_03-20-23_Fe410",
            "04-03-23-0011-11",
            "Good",
            "TEST",
            "extra_sensor",
        ),
        (
            "10_porosity_03-21-23_Fe410",
            "04-03-23-0010-11",
            "Porosity",
            "TEST",
            "missing_images",
        ),
        (
            "10_porosity_03-21-23_Fe410",
            "04-03-23-0012-11",
            "Porosity",
            "VAL",
            "unexpected_audio_rate",
        ),
        (
            "10_undercut_03-22-23_BSK46",
            "04-03-23-0020-00",
            "Undercut",
            "TEST",
            "corrupt_media",
        ),
        (
            "10_undercut_03-22-23_BSK46",
            "04-03-23-0021-00",
            "Undercut",
            "VAL",
            "missing_sensor_column",
        ),
        (
            "10_undercut_03-22-23_BSK46",
            "04-03-23-0022-00",
            "Undercut",
            "TEST",
            "corrupt_sensor",
        ),
    ]
    counts_by_session: dict[str, int] = {}
    for session, *_rest in plan:
        counts_by_session[session] = counts_by_session.get(session, 0) + 1

    manifest_rows: list[dict[str, object]] = []
    for index, (session, sample, category, split, special) in enumerate(plan):
        item_seed = seed + index * 31
        sample_dir = output / session / sample
        sample_dir.mkdir(parents=True, exist_ok=True)

        video = sample_dir / "weld.avi"
        audio = sample_dir / "weld.flac"
        sensor = sample_dir / "sensors.csv"
        images = sample_dir / "images"

        if special == "corrupt_media":
            video.write_bytes(b"not-an-avi-fixture")
            audio.write_bytes(b"not-a-flac-fixture")
        else:
            _write_video(video, fps=31.0 if special == "fps31" else 30.0, seed=item_seed)
            _write_audio(
                audio,
                sample_rate=22_050 if special == "unexpected_audio_rate" else 16_000,
                seed=item_seed,
            )

        if special == "corrupt_sensor":
            # Deliberately invalid UTF-8 after a plausible header. Pandas must fail
            # the probe rather than silently treating the asset as an empty schema.
            sensor.write_bytes(b"Date,Time,Primary Weld Current\n\xff\xfe\xff\x80")
        else:
            _write_sensor(
                sensor,
                seed=item_seed,
                missing_column=special == "missing_sensor_column",
                extra_column=special == "extra_sensor",
            )
        if special != "missing_images":
            _write_images(
                images,
                seed=item_seed,
                corrupt_index=2 if special == "corrupt_media" else None,
            )

        manifest_rows.append(
            {
                "CATEGORY": category,
                "WELD_TYPE": "FILLET",
                "THICKNESS_MM": 7 if "BSK46" not in session else 3,
                "STEEL_TYPE": "FE410" if "Fe410" in session else "BSK46",
                "SAMPLES": counts_by_session[session],
                "CURRENT_A": 182 + index,
                "VOLTAGE_V": 23.8 + 0.1 * (index % 3),
                "GAS_BAR": 1.8,
                "ROBOT_SPEED_CPM": 320 + index,
                "DIRECTORY": session,
                # The audited public manifest already prefixes SUBDIRS with DIRECTORY.
                "SUBDIRS": f"{session}/{sample}",
                "SPLIT": split,
            }
        )

    manifest = output / "manifest.csv"
    pd.DataFrame(manifest_rows).to_csv(manifest, index=False)
    (output / "SYNTHETIC_REAL_SCHEMA_FIXTURE.txt").write_text(
        "Generated regression fixture. Contains no Intel dataset bytes.\n",
        encoding="utf-8",
    )
    return RealSchemaFixtureSummary(
        output=output,
        manifest=manifest,
        samples=len(plan),
        sessions=len(counts_by_session),
    )
